### List all users
GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZTc0MTdkZi1hMWNlLTQ1NDUtODUyOS1kNTRjNmFjYTBmODAiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3NTQ1MTkzNCwiZXhwIjoxNzc1NDUyMjM0fQ.uqixKdqJrjfaiOLnGSxk5pXFxp_VuGDBtmA0zsD3_hI
### Create a user
POST http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZTc0MTdkZi1hMWNlLTQ1NDUtODUyOS1kNTRjNmFjYTBmODAiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3NTQ1MTkzNCwiZXhwIjoxNzc1NDUyMjM0fQ.uqixKdqJrjfaiOLnGSxk5pXFxp_VuGDBtmA0zsD3_hI
Content-Type: application/json

{
    "firstName": "Virat",
    "lastName": "Kohli",
    "email": "virat.kohli@gmail.com",
    "password": "Virat@123",
    "gender": "male",
    "role": "USER",
    "street": "west dehli",
    "city": "west delhi",
    "state": "Delhi",
    "country": "India",
    "zipCode": "124003"
}

### Get a particular user
GET http://localhost:3000/user/0f66bdd6-a988-4c8a-92e1-d893104a4054
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZTc0MTdkZi1hMWNlLTQ1NDUtODUyOS1kNTRjNmFjYTBmODAiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3NTQ1MTkzNCwiZXhwIjoxNzc1NDUyMjM0fQ.uqixKdqJrjfaiOLnGSxk5pXFxp_VuGDBtmA0zsD3_hI

### Update a user
PUT http://localhost:3000/user/c3edce5f-0ee7-42aa-8840-51df7b388d66
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjM2VkY2U1Zi0wZWU3LTQyYWEtODg0MC01MWRmN2IzODhkNjYiLCJlbWFpbCI6ImtsLnJhaHVsQGdtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzc1MjAyNTc3LCJleHAiOjE3NzUyMDI4Nzd9.G42pT1LKdNOsZbE61t3u7FVJhgSDhoR4vBb7ZkpPf-8
Content-Type: application/json

{
    "email":"kannaur@gmail.com"
}

### Soft delete a user
DELETE http://localhost:3000/user/fa04b60a-65d4-452b-9401-627cea25308a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjM2VkY2U1Zi0wZWU3LTQyYWEtODg0MC01MWRmN2IzODhkNjYiLCJlbWFpbCI6ImtsLnJhaHVsQGdtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzc1MjAyNTc3LCJleHAiOjE3NzUyMDI4Nzd9.G42pT1LKdNOsZbE61t3u7FVJhgSDhoR4vBb7ZkpPf-8


### login route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"Admin@123"
}

### get me request
GET http://localhost:3000/user/getme
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZTc0MTdkZi1hMWNlLTQ1NDUtODUyOS1kNTRjNmFjYTBmODAiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3NTQ1MTkzNCwiZXhwIjoxNzc1NDUyMjM0fQ.uqixKdqJrjfaiOLnGSxk5pXFxp_VuGDBtmA0zsD3_hI