### List all users
GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZTc0MTdkZi1hMWNlLTQ1NDUtODUyOS1kNTRjNmFjYTBmODAiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3NTEzMjEyOCwiZXhwIjoxNzc1MTMyNDI4fQ.e0TSDciMPviMi_BdQFejWV-WpTkdGWVbG82D59nG_C4
### Create a user
POST http://localhost:3000/user
Content-Type: application/json

{
    "firstName": "Super",
    "lastName": "Admin",
    "email": "adminl@gmail.com",
    "password": "Admin@123",
    "gender": "male",
    "role": "ADMIN",
    "street": "kheda bazaar",
    "city": "jagadhri",
    "state": "Haryana",
    "country": "India",
    "zipCode": "135003"
}

### Get a particular user
GET http://localhost:3000/user/ae7417df-a1ce-4545-8529-d54c6aca0f80

### Update a user
PUT http://localhost:3000/user/ae7417df-a1ce-4545-8529-d54c6aca0f80
Content-Type: application/json

{
    "email":"admin@gmail.com"
}

### Soft delete a user
DELETE http://localhost:3000/user/fa04b60a-65d4-452b-9401-627cea25308a


### login route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"Admin@123"
}